permalink: "/:title/"
title: " 岁月变迁，沧海桑田 "
url: "http://wusuowei.me"
feed: "/feed.xml"
author:
    name: "楚大爷"
    key: "**"
description: " 没什么想说的 "
copyright: "Copyright 楚大爷 2016 by GitHub and Jekyll"
headdesc: "永远也追不上时间的脚步"
headkeys: "thinks"

redcarpet:
    extensions:
        - "fenced_code_blocks"
